package net.soulteam.soulcore;

import net.md_5.bungee.api.chat.TextComponent;
import net.soulteam.soulcore.bosses.Boss;
import net.soulteam.soulcore.cases.utils.CaseType;
import net.soulteam.soulcore.clans.Clan;
import net.soulteam.soulcore.data.Auction;
import net.soulteam.soulcore.guard.Region;
import net.soulteam.soulcore.utils.enums.Group;
import net.soulteam.soulcore.utils.enums.Version;
import org.bukkit.entity.Player;

public interface User {
	String toString();
	boolean exists();
	String getName();
	String getLastMessage();
	void setLastMessage(final String message);
	Clan getClan();
	void setClan(final String clan);
	boolean isInClan();
	String getPrefix();
	void setPrefix(final String prefix);
	String getIP();
	void setIP(final String ip);
	int getLevel();
	void setLevel(final int lvl);
	void addLevel(final int lvl);
	void takeLevel(final int lvl);
	double getBoost();
	int getXP();
	void setXP(final int xp);
	double getNeedXP(final int lvl);
	int getRefs();
	void setRefs(final int count);
	void addRefs(final int count);
	void takeRefs(final int count);
	String getHomes();
	void setHomes(final String homes);
	void addXP(final int xp);
	int getMoney();
	void setMoney(final double amount);
	void addMoney(final double amount);
	boolean hasMoney(final double need);
	void takeMoney(final double amount);
	void takeXP(final int xp);
	boolean isMsgToggle();
	void setMsgToggle(final boolean value);
	boolean isTpToggle();
	void setTpToggle(final boolean value);
	boolean isGlobalChatEnabled();
	void setGlobalChatEnabled(final boolean value);
	boolean isLocalChatEnabled();
	void setLocalChatEnabled(final boolean value);
	boolean isClanChatEnabled();
	void setClanChatEnabled(final boolean value);
	boolean isShortChatEnabled();
	void setShortChatEnabled(final boolean value);
	boolean isOnline();
	boolean isRefEnabled();
	void setRefEnabled(final boolean value);
	boolean isRefOtherEnabled();
	void setRefOtherEnabled(final boolean value);
	String getLastTell();
	void setLastTell(final String player);
	void setJob(final String job);
	int getJobLevel();
	void setJobLevel(final int level);
	void takeJobLevel(final int level);
	int getJobXP();
	void setJobXP(final int xp);
	void takeJobXP(final int xp);
	void sendMessage(final String message);
	void sendMessage(final TextComponent component);
	Player getPlayer();
	int getRubles();
	Region getInRegion();
	Version getClientVersion();
	Boss getActiveBoss();
	void setActiveBoss(final Boss boss);
	double getBossDamage(final Boss boss);
	void addRubles(final double rubles);
	void takeRubles(final double rubles);
	void addBankMoney(final double money);
	void takeBankMoney(final double money);
	int getBankMoney();
	void sendVersionError(final Version version);
	boolean isClanOwner(final Clan clan);
	Group getGroup();
	boolean isIgnore(final String name);
	int getCases(final CaseType type);
	void giveCases(final CaseType type, final int count);
	void takeCases(final CaseType type, final int count);
	Auction getAuction();
	int getMaxAucItems();
}
